### ISSUE TITLE
Angular4

### ISSUE THREAD

**Issue by Caperious** [manishmct/adyen-payment-angular#1]
Does this work on angular4? When i import `PaymentGatewayModule` i get a ```[ ts ] cannot find 'adyen-payment-angular' module not found ``` error

**Comment by manishmct** [comment]
I have used HttpClientModule which is available from Angular4.3. I have tested the module with Angular5. So i would recommend to use it with V5.

**Comment by manishmct** [comment]
Have imported the module in your main module. Send your code snippet and
error screen shot.
